// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gsbporjmhodqmgamwwjm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdzYnBvcmptaG9kcW1nYW13d2ptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2NjE1OTMsImV4cCI6MjA1OTIzNzU5M30.9RyDdtXpDSXlqB0q-8Sq0DZ5xezHIwRZvzxkjLKGfd0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);